<?php


/**
 * Base class that represents a query for the 'jobeet_affiliate' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.3 on:
 *
 * Mon Jan 23 01:05:28 2012
 *
 * @method     JobeetAffiliateQuery orderById($order = Criteria::ASC) Order by the id column
 * @method     JobeetAffiliateQuery orderByUrl($order = Criteria::ASC) Order by the url column
 * @method     JobeetAffiliateQuery orderByEmail($order = Criteria::ASC) Order by the email column
 * @method     JobeetAffiliateQuery orderByToken($order = Criteria::ASC) Order by the token column
 * @method     JobeetAffiliateQuery orderByIsActive($order = Criteria::ASC) Order by the is_active column
 * @method     JobeetAffiliateQuery orderByCreatedAt($order = Criteria::ASC) Order by the created_at column
 *
 * @method     JobeetAffiliateQuery groupById() Group by the id column
 * @method     JobeetAffiliateQuery groupByUrl() Group by the url column
 * @method     JobeetAffiliateQuery groupByEmail() Group by the email column
 * @method     JobeetAffiliateQuery groupByToken() Group by the token column
 * @method     JobeetAffiliateQuery groupByIsActive() Group by the is_active column
 * @method     JobeetAffiliateQuery groupByCreatedAt() Group by the created_at column
 *
 * @method     JobeetAffiliateQuery leftJoin($relation) Adds a LEFT JOIN clause to the query
 * @method     JobeetAffiliateQuery rightJoin($relation) Adds a RIGHT JOIN clause to the query
 * @method     JobeetAffiliateQuery innerJoin($relation) Adds a INNER JOIN clause to the query
 *
 * @method     JobeetAffiliateQuery leftJoinJobeetCategoryAffiliate($relationAlias = null) Adds a LEFT JOIN clause to the query using the JobeetCategoryAffiliate relation
 * @method     JobeetAffiliateQuery rightJoinJobeetCategoryAffiliate($relationAlias = null) Adds a RIGHT JOIN clause to the query using the JobeetCategoryAffiliate relation
 * @method     JobeetAffiliateQuery innerJoinJobeetCategoryAffiliate($relationAlias = null) Adds a INNER JOIN clause to the query using the JobeetCategoryAffiliate relation
 *
 * @method     JobeetAffiliate findOne(PropelPDO $con = null) Return the first JobeetAffiliate matching the query
 * @method     JobeetAffiliate findOneOrCreate(PropelPDO $con = null) Return the first JobeetAffiliate matching the query, or a new JobeetAffiliate object populated from the query conditions when no match is found
 *
 * @method     JobeetAffiliate findOneById(int $id) Return the first JobeetAffiliate filtered by the id column
 * @method     JobeetAffiliate findOneByUrl(string $url) Return the first JobeetAffiliate filtered by the url column
 * @method     JobeetAffiliate findOneByEmail(string $email) Return the first JobeetAffiliate filtered by the email column
 * @method     JobeetAffiliate findOneByToken(string $token) Return the first JobeetAffiliate filtered by the token column
 * @method     JobeetAffiliate findOneByIsActive(boolean $is_active) Return the first JobeetAffiliate filtered by the is_active column
 * @method     JobeetAffiliate findOneByCreatedAt(string $created_at) Return the first JobeetAffiliate filtered by the created_at column
 *
 * @method     array findById(int $id) Return JobeetAffiliate objects filtered by the id column
 * @method     array findByUrl(string $url) Return JobeetAffiliate objects filtered by the url column
 * @method     array findByEmail(string $email) Return JobeetAffiliate objects filtered by the email column
 * @method     array findByToken(string $token) Return JobeetAffiliate objects filtered by the token column
 * @method     array findByIsActive(boolean $is_active) Return JobeetAffiliate objects filtered by the is_active column
 * @method     array findByCreatedAt(string $created_at) Return JobeetAffiliate objects filtered by the created_at column
 *
 * @package    propel.generator.lib.model.om
 */
abstract class BaseJobeetAffiliateQuery extends ModelCriteria
{
	
	/**
	 * Initializes internal state of BaseJobeetAffiliateQuery object.
	 *
	 * @param     string $dbName The dabase name
	 * @param     string $modelName The phpName of a model, e.g. 'Book'
	 * @param     string $modelAlias The alias for the model in this query, e.g. 'b'
	 */
	public function __construct($dbName = 'propel', $modelName = 'JobeetAffiliate', $modelAlias = null)
	{
		parent::__construct($dbName, $modelName, $modelAlias);
	}

	/**
	 * Returns a new JobeetAffiliateQuery object.
	 *
	 * @param     string $modelAlias The alias of a model in the query
	 * @param     Criteria $criteria Optional Criteria to build the query from
	 *
	 * @return    JobeetAffiliateQuery
	 */
	public static function create($modelAlias = null, $criteria = null)
	{
		if ($criteria instanceof JobeetAffiliateQuery) {
			return $criteria;
		}
		$query = new JobeetAffiliateQuery();
		if (null !== $modelAlias) {
			$query->setModelAlias($modelAlias);
		}
		if ($criteria instanceof Criteria) {
			$query->mergeWith($criteria);
		}
		return $query;
	}

	/**
	 * Find object by primary key.
	 * Propel uses the instance pool to skip the database if the object exists.
	 * Go fast if the query is untouched.
	 *
	 * <code>
	 * $obj  = $c->findPk(12, $con);
	 * </code>
	 *
	 * @param     mixed $key Primary key to use for the query
	 * @param     PropelPDO $con an optional connection object
	 *
	 * @return    JobeetAffiliate|array|mixed the result, formatted by the current formatter
	 */
	public function findPk($key, $con = null)
	{
		if ($key === null) {
			return null;
		}
		if ((null !== ($obj = JobeetAffiliatePeer::getInstanceFromPool((string) $key))) && !$this->formatter) {
			// the object is alredy in the instance pool
			return $obj;
		}
		if ($con === null) {
			$con = Propel::getConnection(JobeetAffiliatePeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}
		$this->basePreSelect($con);
		if ($this->formatter || $this->modelAlias || $this->with || $this->select
		 || $this->selectColumns || $this->asColumns || $this->selectModifiers
		 || $this->map || $this->having || $this->joins) {
			return $this->findPkComplex($key, $con);
		} else {
			return $this->findPkSimple($key, $con);
		}
	}

	/**
	 * Find object by primary key using raw SQL to go fast.
	 * Bypass doSelect() and the object formatter by using generated code.
	 *
	 * @param     mixed $key Primary key to use for the query
	 * @param     PropelPDO $con A connection object
	 *
	 * @return    JobeetAffiliate A model object, or null if the key is not found
	 */
	protected function findPkSimple($key, $con)
	{
		$sql = 'SELECT `ID`, `URL`, `EMAIL`, `TOKEN`, `IS_ACTIVE`, `CREATED_AT` FROM `jobeet_affiliate` WHERE `ID` = :p0';
		try {
			$stmt = $con->prepare($sql);
			$stmt->bindValue(':p0', $key, PDO::PARAM_INT);
			$stmt->execute();
		} catch (Exception $e) {
			Propel::log($e->getMessage(), Propel::LOG_ERR);
			throw new PropelException(sprintf('Unable to execute SELECT statement [%s]', $sql), $e);
		}
		$obj = null;
		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$obj = new JobeetAffiliate();
			$obj->hydrate($row);
			JobeetAffiliatePeer::addInstanceToPool($obj, (string) $row[0]);
		}
		$stmt->closeCursor();

		return $obj;
	}

	/**
	 * Find object by primary key.
	 *
	 * @param     mixed $key Primary key to use for the query
	 * @param     PropelPDO $con A connection object
	 *
	 * @return    JobeetAffiliate|array|mixed the result, formatted by the current formatter
	 */
	protected function findPkComplex($key, $con)
	{
		// As the query uses a PK condition, no limit(1) is necessary.
		$criteria = $this->isKeepQuery() ? clone $this : $this;
		$stmt = $criteria
			->filterByPrimaryKey($key)
			->doSelect($con);
		return $criteria->getFormatter()->init($criteria)->formatOne($stmt);
	}

	/**
	 * Find objects by primary key
	 * <code>
	 * $objs = $c->findPks(array(12, 56, 832), $con);
	 * </code>
	 * @param     array $keys Primary keys to use for the query
	 * @param     PropelPDO $con an optional connection object
	 *
	 * @return    PropelObjectCollection|array|mixed the list of results, formatted by the current formatter
	 */
	public function findPks($keys, $con = null)
	{
		if ($con === null) {
			$con = Propel::getConnection($this->getDbName(), Propel::CONNECTION_READ);
		}
		$this->basePreSelect($con);
		$criteria = $this->isKeepQuery() ? clone $this : $this;
		$stmt = $criteria
			->filterByPrimaryKeys($keys)
			->doSelect($con);
		return $criteria->getFormatter()->init($criteria)->format($stmt);
	}

	/**
	 * Filter the query by primary key
	 *
	 * @param     mixed $key Primary key to use for the query
	 *
	 * @return    JobeetAffiliateQuery The current query, for fluid interface
	 */
	public function filterByPrimaryKey($key)
	{
		return $this->addUsingAlias(JobeetAffiliatePeer::ID, $key, Criteria::EQUAL);
	}

	/**
	 * Filter the query by a list of primary keys
	 *
	 * @param     array $keys The list of primary key to use for the query
	 *
	 * @return    JobeetAffiliateQuery The current query, for fluid interface
	 */
	public function filterByPrimaryKeys($keys)
	{
		return $this->addUsingAlias(JobeetAffiliatePeer::ID, $keys, Criteria::IN);
	}

	/**
	 * Filter the query on the id column
	 *
	 * Example usage:
	 * <code>
	 * $query->filterById(1234); // WHERE id = 1234
	 * $query->filterById(array(12, 34)); // WHERE id IN (12, 34)
	 * $query->filterById(array('min' => 12)); // WHERE id > 12
	 * </code>
	 *
	 * @param     mixed $id The value to use as filter.
	 *              Use scalar values for equality.
	 *              Use array values for in_array() equivalent.
	 *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    JobeetAffiliateQuery The current query, for fluid interface
	 */
	public function filterById($id = null, $comparison = null)
	{
		if (is_array($id) && null === $comparison) {
			$comparison = Criteria::IN;
		}
		return $this->addUsingAlias(JobeetAffiliatePeer::ID, $id, $comparison);
	}

	/**
	 * Filter the query on the url column
	 *
	 * Example usage:
	 * <code>
	 * $query->filterByUrl('fooValue');   // WHERE url = 'fooValue'
	 * $query->filterByUrl('%fooValue%'); // WHERE url LIKE '%fooValue%'
	 * </code>
	 *
	 * @param     string $url The value to use as filter.
	 *              Accepts wildcards (* and % trigger a LIKE)
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    JobeetAffiliateQuery The current query, for fluid interface
	 */
	public function filterByUrl($url = null, $comparison = null)
	{
		if (null === $comparison) {
			if (is_array($url)) {
				$comparison = Criteria::IN;
			} elseif (preg_match('/[\%\*]/', $url)) {
				$url = str_replace('*', '%', $url);
				$comparison = Criteria::LIKE;
			}
		}
		return $this->addUsingAlias(JobeetAffiliatePeer::URL, $url, $comparison);
	}

	/**
	 * Filter the query on the email column
	 *
	 * Example usage:
	 * <code>
	 * $query->filterByEmail('fooValue');   // WHERE email = 'fooValue'
	 * $query->filterByEmail('%fooValue%'); // WHERE email LIKE '%fooValue%'
	 * </code>
	 *
	 * @param     string $email The value to use as filter.
	 *              Accepts wildcards (* and % trigger a LIKE)
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    JobeetAffiliateQuery The current query, for fluid interface
	 */
	public function filterByEmail($email = null, $comparison = null)
	{
		if (null === $comparison) {
			if (is_array($email)) {
				$comparison = Criteria::IN;
			} elseif (preg_match('/[\%\*]/', $email)) {
				$email = str_replace('*', '%', $email);
				$comparison = Criteria::LIKE;
			}
		}
		return $this->addUsingAlias(JobeetAffiliatePeer::EMAIL, $email, $comparison);
	}

	/**
	 * Filter the query on the token column
	 *
	 * Example usage:
	 * <code>
	 * $query->filterByToken('fooValue');   // WHERE token = 'fooValue'
	 * $query->filterByToken('%fooValue%'); // WHERE token LIKE '%fooValue%'
	 * </code>
	 *
	 * @param     string $token The value to use as filter.
	 *              Accepts wildcards (* and % trigger a LIKE)
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    JobeetAffiliateQuery The current query, for fluid interface
	 */
	public function filterByToken($token = null, $comparison = null)
	{
		if (null === $comparison) {
			if (is_array($token)) {
				$comparison = Criteria::IN;
			} elseif (preg_match('/[\%\*]/', $token)) {
				$token = str_replace('*', '%', $token);
				$comparison = Criteria::LIKE;
			}
		}
		return $this->addUsingAlias(JobeetAffiliatePeer::TOKEN, $token, $comparison);
	}

	/**
	 * Filter the query on the is_active column
	 *
	 * Example usage:
	 * <code>
	 * $query->filterByIsActive(true); // WHERE is_active = true
	 * $query->filterByIsActive('yes'); // WHERE is_active = true
	 * </code>
	 *
	 * @param     boolean|string $isActive The value to use as filter.
	 *              Non-boolean arguments are converted using the following rules:
	 *                * 1, '1', 'true',  'on',  and 'yes' are converted to boolean true
	 *                * 0, '0', 'false', 'off', and 'no'  are converted to boolean false
	 *              Check on string values is case insensitive (so 'FaLsE' is seen as 'false').
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    JobeetAffiliateQuery The current query, for fluid interface
	 */
	public function filterByIsActive($isActive = null, $comparison = null)
	{
		if (is_string($isActive)) {
			$is_active = in_array(strtolower($isActive), array('false', 'off', '-', 'no', 'n', '0', '')) ? false : true;
		}
		return $this->addUsingAlias(JobeetAffiliatePeer::IS_ACTIVE, $isActive, $comparison);
	}

	/**
	 * Filter the query on the created_at column
	 *
	 * Example usage:
	 * <code>
	 * $query->filterByCreatedAt('2011-03-14'); // WHERE created_at = '2011-03-14'
	 * $query->filterByCreatedAt('now'); // WHERE created_at = '2011-03-14'
	 * $query->filterByCreatedAt(array('max' => 'yesterday')); // WHERE created_at > '2011-03-13'
	 * </code>
	 *
	 * @param     mixed $createdAt The value to use as filter.
	 *              Values can be integers (unix timestamps), DateTime objects, or strings.
	 *              Empty strings are treated as NULL.
	 *              Use scalar values for equality.
	 *              Use array values for in_array() equivalent.
	 *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    JobeetAffiliateQuery The current query, for fluid interface
	 */
	public function filterByCreatedAt($createdAt = null, $comparison = null)
	{
		if (is_array($createdAt)) {
			$useMinMax = false;
			if (isset($createdAt['min'])) {
				$this->addUsingAlias(JobeetAffiliatePeer::CREATED_AT, $createdAt['min'], Criteria::GREATER_EQUAL);
				$useMinMax = true;
			}
			if (isset($createdAt['max'])) {
				$this->addUsingAlias(JobeetAffiliatePeer::CREATED_AT, $createdAt['max'], Criteria::LESS_EQUAL);
				$useMinMax = true;
			}
			if ($useMinMax) {
				return $this;
			}
			if (null === $comparison) {
				$comparison = Criteria::IN;
			}
		}
		return $this->addUsingAlias(JobeetAffiliatePeer::CREATED_AT, $createdAt, $comparison);
	}

	/**
	 * Filter the query by a related JobeetCategoryAffiliate object
	 *
	 * @param     JobeetCategoryAffiliate $jobeetCategoryAffiliate  the related object to use as filter
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    JobeetAffiliateQuery The current query, for fluid interface
	 */
	public function filterByJobeetCategoryAffiliate($jobeetCategoryAffiliate, $comparison = null)
	{
		if ($jobeetCategoryAffiliate instanceof JobeetCategoryAffiliate) {
			return $this
				->addUsingAlias(JobeetAffiliatePeer::ID, $jobeetCategoryAffiliate->getAffiliateId(), $comparison);
		} elseif ($jobeetCategoryAffiliate instanceof PropelCollection) {
			return $this
				->useJobeetCategoryAffiliateQuery()
				->filterByPrimaryKeys($jobeetCategoryAffiliate->getPrimaryKeys())
				->endUse();
		} else {
			throw new PropelException('filterByJobeetCategoryAffiliate() only accepts arguments of type JobeetCategoryAffiliate or PropelCollection');
		}
	}

	/**
	 * Adds a JOIN clause to the query using the JobeetCategoryAffiliate relation
	 *
	 * @param     string $relationAlias optional alias for the relation
	 * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
	 *
	 * @return    JobeetAffiliateQuery The current query, for fluid interface
	 */
	public function joinJobeetCategoryAffiliate($relationAlias = null, $joinType = Criteria::INNER_JOIN)
	{
		$tableMap = $this->getTableMap();
		$relationMap = $tableMap->getRelation('JobeetCategoryAffiliate');

		// create a ModelJoin object for this join
		$join = new ModelJoin();
		$join->setJoinType($joinType);
		$join->setRelationMap($relationMap, $this->useAliasInSQL ? $this->getModelAlias() : null, $relationAlias);
		if ($previousJoin = $this->getPreviousJoin()) {
			$join->setPreviousJoin($previousJoin);
		}

		// add the ModelJoin to the current object
		if($relationAlias) {
			$this->addAlias($relationAlias, $relationMap->getRightTable()->getName());
			$this->addJoinObject($join, $relationAlias);
		} else {
			$this->addJoinObject($join, 'JobeetCategoryAffiliate');
		}

		return $this;
	}

	/**
	 * Use the JobeetCategoryAffiliate relation JobeetCategoryAffiliate object
	 *
	 * @see       useQuery()
	 *
	 * @param     string $relationAlias optional alias for the relation,
	 *                                   to be used as main alias in the secondary query
	 * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
	 *
	 * @return    JobeetCategoryAffiliateQuery A secondary query class using the current class as primary query
	 */
	public function useJobeetCategoryAffiliateQuery($relationAlias = null, $joinType = Criteria::INNER_JOIN)
	{
		return $this
			->joinJobeetCategoryAffiliate($relationAlias, $joinType)
			->useQuery($relationAlias ? $relationAlias : 'JobeetCategoryAffiliate', 'JobeetCategoryAffiliateQuery');
	}

	/**
	 * Exclude object from result
	 *
	 * @param     JobeetAffiliate $jobeetAffiliate Object to remove from the list of results
	 *
	 * @return    JobeetAffiliateQuery The current query, for fluid interface
	 */
	public function prune($jobeetAffiliate = null)
	{
		if ($jobeetAffiliate) {
			$this->addUsingAlias(JobeetAffiliatePeer::ID, $jobeetAffiliate->getId(), Criteria::NOT_EQUAL);
		}

		return $this;
	}

} // BaseJobeetAffiliateQuery