generator:
  class: sfPropelGenerator
  param:
    model_class:           JobeetAffiliate
    theme:                 admin15
    non_verbose_templates: true
    with_show:             false
    singular:              JobeetAffiliate
    plural:                JobeetAffiliates
    route_prefix:          jobeet_affiliate
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      fields:
        is_active: { label: Active? }
      list:
        title:   Affiliate Management
        display: [is_active, url, email, token]
        sort:    [is_active]
        object_actions:
          activate:   ~
          deactivate: ~
        batch_actions:
          activate:   ~
          deactivate: ~
        actions: {}
      filter:
        display: [url, email, is_active]