<?php



/**
 * Skeleton subclass for performing query and update operations on the 'jobeet_category_affiliate' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.3 on:
 *
 * Sun Jan 22 15:48:33 2012
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class JobeetCategoryAffiliateQuery extends BaseJobeetCategoryAffiliateQuery {

} // JobeetCategoryAffiliateQuery
